### ISSUE TITLE
Keep current configuration when globally enabling a feature flag

### ISSUE THREAD

**Issue by ceritium** [jnunemaker/flipper#632] opened 2022-05-09 10:05 UTC
When globally enabling a feature flag, the existing configuration is deleted. It would be desirable to keep the current configuration to avoid losing the existing config when someone enables it globally by mistake or just like to recover the previous config.

What do you think?

**Comment by jnunemaker** [comment] 2022-05-09 12:49
The problem is its weird in practice. Say you enable a few actors individually and 30% of actors. Then you click enable. Something's wrong and you don't want it to be. 

So you click disable. What is your expectation? Mine would be it is entirely off. I would not expect it to go back to previous state. If its not disable, then it means we have to add something new to rollback to previous state. Can you keep rolling back or just one rollback? 

Either way you have to build things into the adapter level to store one or more rollback states. Then you have to add a rollback methods in all the adapters, DSLs, UI and API. It's a huge undertaking. I don't think it is as simple as just making disable go back to previous state (which also would break backwards compatibility). 

## Cloud Solution 

To me this is something solved with an audit log and rollback. For www.flippercloud.io, this is what we did. 

We have an audit list for each environment. 

![audit list](https://user-images.githubusercontent.com/235/167410197-9877e779-7f7a-4349-8b40-e3ea2d44a796.png)

If you click "View or rollback" you can see what the state of configuration was at that point and easily roll back to it. 

![audit view](https://user-images.githubusercontent.com/235/167410198-90f443fc-3937-4411-8df3-8e7b8b508175.png)

It feels awkward and breaks expectations to disable and go back to previous state. Having separate functionality makes the most sense to me. But I don't really want to maintain audit log and rollback for every single adapter, thus I whipped it together in cloud so I could just do it once.

## Roll your own solution

Another option is to roll your own. If you [instrument](https://www.flippercloud.io/docs/instrumentation) with `ActiveSupport::Notifications` and [subscribe to the instrumentation](https://github.com/jnunemaker/flipper/blob/4b481e402b45e560e4b34ab807f06768c58f4daa/examples/instrumentation.rb) , you can create audit logs. 

```ruby
require 'active_support/notifications'

class FlipperSubscriber
  def call(*args)
    event = ActiveSupport::Notifications::Event.new(*args)
    # do something here to serialize gates hash into your database
    puts event.inspect
  end

  ActiveSupport::Notifications.subscribe(/flipper/, new)
end

require 'flipper'
require 'flipper/adapters/instrumented'
adapter = Flipper::Adapters::Memory.new
flipper = Flipper.new(adapter, instrumenter: ActiveSupport::Notifications)
flipper.enable(:search)
flipper.enabled?(:search)

# events will start getting printed out
```

If you want to then rollback, those audit logs can reasonably store the state of configuration in the audit log (in postgres it could be a jsonb or in other databases just serialize json somewhere). 

Getting the gates hash is possible by doing this:

```ruby
flipper.adapter.get(flipper[feature.key]) # hash of gate key => value
```

You can serialize that in your data store. Rehydrating that gates hash into something useful is easy:

```ruby
# A recreation of the flipper feature at this point in time.
adapter = Flipper::Adapters::Memory.new({
  feature.key => HashWithIndifferentAccess.new(gates_hash),
})
Flipper::Feature.new(feature.key, adapter)
```

Rolling back isn't too bad either as you can use some flipper internals:

```ruby
# current config
local_gate_values = Flipper::GateValues.new(HashWithIndifferentAccess.new(flipper.adapter.get(flipper[feature.key])))

# config to rollback to
remote_gate_values = Flipper::GateValues.new(HashWithIndifferentAccess.new(feature_audit.gates_hash))

# sync them up
synchronizer = Flipper::Adapters::Sync::FeatureSynchronizer.new(flipper_feature, local_gate_values, remote_gate_values)
synchronizer.call
```

All that code is pulled from flipper cloud so it should be trustworthy and gives you an idea. 

## Wrap up

Any thoughts on any of that or strong feelings to the contrary? By no means do I assume I've thought of all the options here. 😄

**Comment by jnunemaker** [comment] 2022-05-09 12:49
Closing to keep tidy but happy to keep the conversation flowing.

**Closed by jnunemaker** 2022-05-09 12:49 UTC

**Comment by ceritium** [comment] 2022-05-19 10:46
Hi, thanks for your detailed response.

I was thinking in something simpler, in my case I am using the Active Record adapter, I did a couple of changes:
```diff
diff --git a/lib/flipper/adapters/active_record.rb b/lib/flipper/adapters/active_record.rb
index a433cbef..4c2c1fbb 100644
--- a/lib/flipper/adapters/active_record.rb
+++ b/lib/flipper/adapters/active_record.rb
@@ -127,7 +127,7 @@ module Flipper
       def enable(feature, gate, thing)
         case gate.data_type
         when :boolean
-          set(feature, gate, thing, clear: true)
+          set(feature, gate, thing, clear: false)
         when :integer
           set(feature, gate, thing)
         when :set
@@ -149,7 +149,7 @@ module Flipper
       def disable(feature, gate, thing)
         case gate.data_type
         when :boolean
-          clear(feature)
+          @gate_class.where(feature_key: feature.key, key: gate.key).destroy_all
         when :integer
           set(feature, gate, thing)
         when :set
(END)
```

This approach lets me enable/disable a FF without losing the individual actors or % configuration. 
Of course, my approach would require changing it on several adapters too to keep it coherent, and maybe I am missing something important.

Many thanks for your help.
