### ISSUE TITLE
Is it possible to configure flipper to work for anonymous users?

### ISSUE THREAD

**Issue by rsaunders100** [jnunemaker/flipper#128] opened 2016-06-07 16:07 UTC
We have our flipper id set to the user Id

```
def flipper_id
    "user:#{id}"
end
```

This is good for [Percentage of Actors](https://github.com/jnunemaker/flipper/blob/master/docs/Gates.md#4-percentage-of-actors)

However, we want to roll out a feature for a percentage of anonymous users.  We have a 'guest id' for these users.  We have thought of a few it might work, none of them ideal:

1. **Use % of time** - This means the feature might toggle for a given user over time.  We want the user to see the same features all the time.
2. **Make a new group** - I think we may be able to make a custom group called '50% of all anonymous users' and define it as `(hash('guest id') % 2 == 0)`.  This might work but it's not very scalable and feels a bit hacky.
3. **Make a new instance of flipper that uses the guest id as the flipper_id**.  This will be very difficult for us.

Is there a better solution we have not thought of?

**Comment by jnunemaker** [comment] 2016-06-08 19:48
1. Means it won't be consistently on for a user, which definitely isn't ideal if UI changes based on feature enabledness. (Think feature enabled shows form, but feature disabled when request is submitted so request is then denied). 
2. Definitely hacky. 
3. No necessary.

> Is there a better solution we have not thought of?

Do anonymous users get a session? You could store a random key in the session and then enable for a percentage of actors based on that. Hacked code below, but hopefully it gives you some ideas.

```ruby
require "securerandom"
class FlipperSession
  SESSION_KEY = "_flipper_id".freeze

  def self.session_key
    SESSION_KEY
  end

  def self.generate_id
    SecureRandom.uuid # maybe something better? I don't know...
  end

  attr_reader :id
  
  def initialize(id)
    @id = id
  end

  def flipper_id 
    "FlipperSession/#{@id}"
  end
end

# In application controller
def flipper_session_id
  session[FlipperSession.session_key] ||= FlipperSession.generate_id
end
helper_method :flipper_session_id

def flipper_session
  @flipper_session ||= FlipperSession.new(flipper_session_id)
end
helper_method :flipper_session

# in controller or helper or view
flipper.enabled?(:some_feature, flipper_session)
```

Flipper really just needs an actor with a flipper_id, so just give it something that is deterministic per user whether they are signed in or out. Closing the issue, but please let me know if I wasn't clear. Also, if you try this and it works out (or doesn't), let me know as I am always curious. We use a modified version of this at GitHub and it has been fine.

**Closed by jnunemaker** 2016-06-08 19:48 UTC

**Comment by oboxodo** [comment] 2017-08-28 05:03
Hey, I'm thinking of using Flipper and found this same issue about supporting logged out visitors.

One issue to keep in mind is maintaining the features stable for a visitor before and after logging in. If I have a new gate which I want to enable for 10% users, and this feature has impact both for logged in and logged out users in our UI, is there a way to account for that?

The best I can think of is to use this suggested `FlipperSession` regardless of the user being logged in or not, with a caveat: we should store the `flipper_session_id` in a `user.flipper_id` column whenever that column is `nil`.

That way, a new user signing up would have the same experience before and after signing up. An existing user who logs in but has never had the `flipper_id` assigned will have it assigned from the one generated for the logged out session, so gets the same experience too. (Although... can't remember if Devise - in my case - will reset the full session on log in meaning I'll lose the generated id.)

The problem is for existing users who already have a `flipper_id` assigned. Those might have some features enabled while logged out, and some others enabled while logged in.

Any ideas?
