### ISSUE TITLE
Enabling Flipper for multiple IDs?

### ISSUE THREAD

**Issue by phstc** [jnunemaker/flipper#656] opened 2022-08-15 12:59 UTC
For my use case, I need to enable Flipper for specific users or organizations.

I can add `||` and check for both, but that can add some complexity.

```ruby
if Flipper.enabled? :search, current_user || if Flipper.enabled? :search, current_user.organization
```

Is there a way to simplify that?

If not, I was wondering if `flipper_id` could return a `string` (current implementation) or a `string[]`.

```ruby
def flipper_id
  [id.to_s, organization_id.to_s]
end
```

Then Flipper could check on both. 

Any thoughts?

**Comment by jnunemaker** [comment] 2022-08-15 17:07
I've considered adding `Flipper.enabled?(:search, [current_user, current_user.org])` but there was a reason I didn't. Unfortunately I'm failing to remember and its driving me nuts. 

I don't want to change the return value of flipper_id as that would ripple through the library. Everywhere would need to start using the first value instead of all and it would have to be clear in docs that first is used for most things but all are used for `enabled?`. 

I think that #557 will help with this use case as then you could add `organization_id` as an attribute and enable based on that too. We are going to regroup on expressions/rules soon and try to get it shipped. Its mostly just the UI that is preventing a first release of it.

**Comment by phstc** [comment] 2022-08-15 17:27
That makes! Thank you

For now, I'm considering wrapping `enabled?`  through `Feature.enabled?` instead of `Flipper.enabled?`.

```ruby
# pseudo code 

def enabled?(name, *args)
   return Flipper.enabled?(name, *args) unless args.last.is_a?(User)

   args_with_box = args.dup
   args_with_box.pop # remove user to be replaced with org
   args_with_box.push args.last.org # add org

   return Flipper.enabled?(name, *args) || Flipper.enabled?(name, *args_with_org)
end
```
Any thoughts?

**Comment by jnunemaker** [comment] 2022-08-16 18:27
I'd probably just do:

```ruby
def enabled?(name, actors)
  actors.any? { |actor| Flipper.enabled?(name, actor) }
end
```

Or if you want to force always checking the user's org too:

```ruby
# * to always get array
def enabled?(name, *actors)
  # flatten so passing array or single works
  actors = actors.flatten
  # get the user actors
  user_actors = actors.select { |actor| actor.is_a?(User) }
  # make sure the orgs are added automatically
  user_actors.each { |user_actor| actors << user_actor.org unless actors.include?(user_actor.org) }
  # check them all now
  actors.any? { |actor| Flipper.enabled?(name, actor) }
end
```

**Comment by jnunemaker** [comment] 2022-08-16 18:28
Closing to keep tidy but still very happy to respond.

**Closed** 2022-08-16 18:28 UTC

**Comment by phstc** [comment] 2022-08-16 18:40
That's much simpler, thank you! I was copying the signature from here https://github.com/jnunemaker/flipper/blob/3dbd19323b50248eb090206b102dce4909d85223/lib/flipper/dsl.rb#L35 I wasn't sure what `*args` was about, but in our case, the last is always the actor.

**Comment by chernenkov-ayu-sbmt** [comment] 2024-05-14 11:02
*Warning!* If you use code like the one above (`if Flipper.enabled?(:x, actor1) || Flipper.enabled?(:x, actor2)`), it will break a percentage configuration of the feature `:x`. E.g. if `:x` is enabled for 50% of the time, then checking it with the above code will actually result in 75% of `if`-block executions (it is like tossing the coin twice).

**Comment by chernenkov-ayu-sbmt** [comment] 2024-05-14 11:06
> it will break a percentage configuration of the feature

@jnunemaker With that said, I believe that multi-actor feature checking must be implemented by the Flipper gem itself to avoid unintended behaviour of calling `Flipper.enabled?` multiple times by a library user.

**Comment by bkeepers** [comment] 2024-05-14 11:11
@chernenkov-ayu-sbmt You can pass multiple actor IDs to `enabled?` now (cc #710)

```ruby
Flipper.enabled?(:x, [actor1, actor2])
```

See https://www.flippercloud.io/docs/features/actors

**Comment by chernenkov-ayu-sbmt** [comment] 2024-05-14 12:09
@bkeepers Great! Thank you very much for letting me know about it!
