### ISSUE TITLE
New features not appearing on index page in 0.25.2

### ISSUE THREAD

**Issue by garyjohnson** [jnunemaker/flipper#662] opened 2022-08-31 19:54 UTC
# Problem
After upgrading to 0.25.2 across a couple apps, we noticed that when adding a new feature (through `flipper-ui`), we could make changes to the flipper (add new actors, etc), but when returning to the index page, new features were not listed.

Adding the feature again would show the individual feature edit page with the previous settings still respected, but again it would not show up on the index page.

When downgrading back to 0.25.1, the previously added feature still didn't appear, but when attempting to add it once again under 0.25.1 it finally showed up on the index page (still retaining the settings from 0.25.2)

# Reproduction Steps

1. Open index page from flipper-ui (`/features`)
2. Click 'Add Feature'
3. On the create feature page (`/features/new`), enter a feature name and click `Add Feature`
4. Add an actor on the feature edit page (`/features/<feature name>`), so that you can determine the settings are retained
5. Navigate back to the index page (`/features`)
6. Note the new feature is not there
7. Go through steps 1-6 again, but note that the previous settings were retained on the edit page

# Detail

We're using Redis as the backend for Flipper.

Versions
```
flipper=0.25.2
flipper-ui=0.25.2
flipper-redis=0.25.2
redis=4.8.0
redis-namespace=1.9.0
rails=6.1.6.1
ruby=3.1.2
```

**Comment by dmarcoux** [comment] 2022-09-03 15:20
I see that you're using Redis 4.8.0, so this issue must be related to the changes in #660.

**Comment by gingerlime** [comment] 2022-09-06 07:31
@dmarcoux didn't #660 actually fix the issue with redis 4.8.0 and was included in flipper 0.25.2 ? (I didn't bump into this issue, but was just checking for any open issues related to 0.25.2 before upgrading)

**Comment by jnunemaker** [comment] 2022-09-09 12:40
@garyjohnson I can't reproduce this. I setup a stock Rails app with redis 4.8, ruby 3.1 and flipper, flipper-ui and flipper-redis gems 0.25.2. 

I went to features, add new feature, added feature, added actor, went back to index and got this:

![Screen Shot 2022-09-09 at 8 37 25 AM](https://user-images.githubusercontent.com/235/189351545-1285532b-55c0-4426-ad38-96a32ea28bb1.png)

I've done it multiple times and each feature shows up. Something else weird must be going on -- maybe with redis-namespace? 

Can you drop your redis configuration in here and any specific flipper config you may have? 

I'm closing the issue to keep things tidy but happy to keep helping and will re-open if we can confirm the problem is with flipper.

**Closed by jnunemaker** 2022-09-09 12:40 UTC

**Comment by garyjohnson** [comment] 2022-09-09 13:20
Thanks for looking into this. I’ll work on setting up a test with / without redis-namespace and see if it’s needed for reproduction.

**Comment by VeraCologne** [comment] 2022-09-13 10:12
I can reproduce this with redis-namespace. If I create an adapter with Redis::Namespace and add features, they do not appear in my index. If I then create an adapter without the namespace, the features I added in the namespaced adapter appear in my index (along with new ones I add). So it looks like the features get created but not in the namespace I want them. 

I have set up a new Rails app with just flipper, flipper-redis, flipper-ui and redis-namespace as extra gems: https://github.com/VeraCologne/redis-flipper-namespace-test

Tested with redis-server version 5.0.5

versions in my gemfile: 
- redis 4.8.0
- flipper 0.25.2
- redis-namespace 1.9.0

this is my config/initializers/flipper.rb
```
require 'flipper/adapters/redis'

options = {
  url: 'redis://127.0.0.1'
}

# this works
adapter = Flipper::Adapters::Redis.new(Redis.new(options))

# this does not work
# adapter = Flipper::Adapters::Redis.new(Redis::Namespace.new('test_flipper', redis: Redis.new(options)))

Flipper.configure do |config|
  config.default { Flipper.new(adapter) }
end

features = %w[foo bar baz]

features.each { |feature| Flipper.add feature }
```

**Comment by jtokoph** [comment] 2022-09-18 20:08
@jnunemaker The issue here seems to be that redis-namespace doesn't handle `sadd?` yet, so its not applying the namespace when making the `sadd?` call.

I'm temporarily working around this with a monkey patch in my initializer:

```ruby
module Flipper
  module Adapters
    class Redis
      private
      def redis_sadd_returns_boolean?
        false
      end
    end
  end
end
```
