### ISSUE TITLE
Actors "placeholder"? 

### ISSUE THREAD

**Issue by phstc** [jnunemaker/flipper#657] opened 2022-08-15 15:08 UTC
It is difficult to identify who the actors are. I understand we can use `User;uuid`, etc., but still, it does not tell which user.

![image](https://user-images.githubusercontent.com/105652/184639802-56667e86-b329-4247-91dc-354d4062c291.png)

I was wondering if it would be interesting to allow configuring an `actor_display_placeholder` so that we can show the name instead or any other combination that can be useful when listing actors. 

```ruby
flipper.actor_display_placeholder = proc { |flipper_id| User.find(flipper_id).name }
```

**Comment by jnunemaker** [comment] 2022-08-15 16:54
Agreed. This would be nice. Closing as duplicate of #389. But I'd be open to a PR. 

Instead of a one by one, which would lead to an N+1 loading issue when showing actors, I'd do something that is bulk like how we load the descriptions for features.

Configuration:
https://github.com/jnunemaker/flipper/blob/7727ca686462864e123ac27c60c3bc86f48546f9/lib/flipper/ui/configuration.rb#L74

Example usage:
https://github.com/jnunemaker/flipper/blob/7727ca686462864e123ac27c60c3bc86f48546f9/examples/ui/basic.ru#L30-L41

How the UI action loads them in bulk:
https://github.com/jnunemaker/flipper/blob/7727ca686462864e123ac27c60c3bc86f48546f9/lib/flipper/ui/actions/features.rb#L14-L18

I'd maybe call it `actor_names_source` to match `descriptions_source`. I'd have the method take an array of flipper_id's and return a hash of flipper_id => String name. Then the UI can use the name instead of flipper_id or show both (e.g. `John Nunemaker (User;1)`).

**Comment by jnunemaker** [comment] 2022-08-15 16:55
www.flippercloud.io allows defining a name for each actor and I always use Cloud so that's probably why I haven't gotten to this yet.

**Closed by jnunemaker** 2022-08-15 16:54 UTC

**Comment by phstc** [comment] 2022-08-15 17:08
@jnunemaker thank you for the quick reply!

> Instead of a one by one, which would lead to an N+1

For my use case, I'm not too worried about N+1, given I usually have just a few actors - and I don't open the page listing actors that often. But I understand some users may have many.

What I like about the proc is that we can leave it up for users to implement in the way they want. 

For example, with the descriptors, it is key->value (string->string), whereas, with a proc, I can have more flexibility:

```ruby
flipper.actor_display_placeholder = proc do |flipper_id| 
   user = User.find(flipper_id).name # or user = USER_DESCRIPTORS[user.id]

   "#{user.name}-this-and-that-#{user.org.name}"
end
```

**Comment by jnunemaker** [comment] 2022-08-16 18:55
I can't merge anything that is N+1. Might not affect you but will affect others. The bulk version of the proc that I'm proposing is the same thing, you just make it work for an array. 

```ruby
# bulk version that does the same thing and never ends up in n+1;
# if you have actors other than User, you could group on the constant (User, Org, etc.) and do lookups for others.
flipper.actor_names_source = proc do |flipper_ids|
  # get the active record ids from flipper ids
  ids = flipper_ids.map { |flipper_id| flipper_id.split(';', 2).last }

  # find the users
  users = User.where(id: ids)

  # return hash of flipper_id => custom name
  users.inject({}) do |hash, user|
    hash[user.flipper_id] = "#{user.name}-this-and-that-#{user.org.name}"
    hash
  end
end
```

**Comment by phstc** [comment] 2022-08-16 18:59
That's not really N+1. Everyone can implement that differently. It is just a callback for formatting rows. But I hear you.

I misread your initial comment, I thought you were suggesting something key-value, and that wouldn't do it. 

The bulk version would work for me. It's solid.

**Comment by jnunemaker** [comment] 2023-11-04 17:55
Merged https://github.com/flippercloud/flipper/pull/737 which handles this. Should be released soon.
