### ISSUE TITLE
Getting `Flipper::Middleware::Memoizer appears to be running twice` warning on stock config.

### ISSUE THREAD

**Issue by craigmcnamara** [jnunemaker/flipper#558] opened 2021-09-07 17:26 UTC
I'm using the stock config and the error message is still popping up in CI.

My initializer is as follows:

```
require 'flipper'
require 'flipper/ui'
require 'flipper/adapters/active_record'
```

Relevant `Gemfile.lock`:

```
    flipper (0.22.1)
    flipper-active_record (0.22.1)
      activerecord (>= 4.2, < 7)
      flipper (~> 0.22.1)
    flipper-ui (0.22.1)
      erubi (>= 1.0.0, < 2.0.0)
      flipper (~> 0.22.1)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, < 2.2.0)
```

My read of the pull request that was mentioned is that I shouldn't get this warning, but I may be misunderstanding. I'm happy to help with a pull request if there is an issue that needs to be addressed.

**Comment by bkeepers** [comment] 2021-09-08 11:17
Hey @craigmcnamara, thanks for opening an issue. When you run `$ rake middleware` do you see `use Flipper::Middleware::Memoizer` listed twice?

I don't think it's related, but you can remove all the requires in your initializer. Those will get required automatically when gems load as part of the Rails bootstrap process.

**Comment by craigmcnamara** [comment] 2021-09-09 18:55
Only listed once. I used to have a custom middleware configuration but I've removed all of that.

```
# bin/rake middleware
Running via Spring preloader in process 198
use Webpacker::DevServerProxy
use Honeybadger::Rack::UserInformer
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::ErrorNotifier
use ActionDispatch::HostAuthorization
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use Rack::RootDomainRedirect
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::ActionableExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use ActionDispatch::PermissionsPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use Flipper::Middleware::Memoizer
use ApolloUploadServer::Middleware
use Bullet::Rack
use OmniAuth::Strategies::GoogleOauth2
use OmniAuth::Strategies::Facebook
```

**Comment by craigmcnamara** [comment] 2021-10-01 03:49
I removed any extra initializer and I'm still seeing the Flipper error. Seems harmless, as Flipper seems to behave, but it's a bit noisy.

**Comment by antonzagorskii** [comment] 2021-10-14 11:54
i have the same problem ^

**Comment by antonzagorskii** [comment] 2021-10-14 11:55
i have the same problem ^

**Comment by malclocke** [comment] 2021-11-03 03:29
I'm seeing this too in an app with no specific config for adding the middleware.  I haven't been able to get totally to the bottom of the issue but I've worked this much out:
- `Flipper::Middleware::Memoizer#call` is _not_ getting called twice on each request, and the middleware is only being loaded once.
- If I make successive calls to the same endpoint the value of `flipper.memoizing?` at https://github.com/jnunemaker/flipper/blob/master/lib/flipper/middleware/memoizer.rb#L65 toggles between `true` and `false` with each request.  So on the first request I don't get the `warn`, on the second request I get `warn`, third request I don't, fourth I do, etc.

I'll have a bit more of a dig if I get time but maybe this info is useful.  I also checked to see if I could bisect to a particular commit but I think this issue has been there since the warning was introduced at 63fd6a96c

**Comment by jnunemaker** [comment] 2021-11-03 03:44
Thanks!

What server are you using (puma? Unicorn? Passenger?) and what config?

**Comment by maxjacobson** [comment] 2021-11-03 19:43
FWIW, we were having the same issue and resolved it by adding

```ruby
config.flipper.preload = false
```

in our `config/application.rb`. Previously we weren't specifying that option at all.

I don't really understand why that helped if I'm being honest, but just sharing as something to try and perhaps a clue.

**Comment by malclocke** [comment] 2021-11-03 21:22
@jnunemaker we're using puma.  It smelled a bit like a threading bug initially to me but I get the same issue running our app with webrick so I don't think it is.

The issue for us is there is something in our middleware stack, or elsewhere, that is causing this block passed to `Rack::BodyProxy` to not get called.

https://github.com/jnunemaker/flipper/blob/3dfa46ac33ddf4648a90b9b7553ebe6b874f1725/lib/flipper/middleware/memoizer.rb#L78-L80

I don't see the same issue in a minimal rails test case, so I think it's likely one of these middlewares.  Here's the list of middlewares that are common to our app and the list reported by @craigmcnamara above, and are not part of the minimal Rails middleware stack.
```
	use ActionDispatch::Flash
	use ActiveRecord::Migration::CheckPending
	use ActiveSupport::Cache::Strategy::LocalCache::Middleware
	use Bullet::Rack
	use OmniAuth::Strategies::Facebook
	use RequestStore::Middleware
	use Sprockets::Rails::QuietAssets
	use Warden::Manager
```
I'll keep trying to create a minimal test case.

**Comment by jnunemaker** [comment] 2021-11-03 21:43
Oh. Just occurred to me. Might be that you are running multiple processes in puma or unicron and we warn for each one. I'll test this theory and report back but my gut says that is it. 

Easy way to test is to change process count to 1 and see what happens. I can drop puma or unicorn config here when I'm back at computer.

**Comment by malclocke** [comment] 2021-11-03 21:53
Issue occurs for me when running `bundle exec puma -w 0 -t 1:1`

And issue still occurs when I remove puma and run with webrick, which afaik is single process single thread.

**Comment by malclocke** [comment] 2021-11-04 01:45
OK, I've isolated this in my case to another middleware in the stack misbehaving.  In my case it's `ScoutApm::Instant::Middleware` which is inserted below flipper in the stack.  This middlware is losing the reference to the `Rack::BodyProxy` that flipper creates, and so the `close` block is never getting called.

I expect this could be the same case for others with this issue, but perhaps different middlewares that are the culprit.

Anyway, in my case this is a bug in the Scout APM gem, not flipper.

**Comment by bkeepers** [comment] 2021-11-04 16:39
@malclocke great, thanks for taking time to track that down! I wonder if there is anything we can do to work around misbehaving middleware. 🤔

**Comment by jnunemaker** [comment] 2021-11-04 18:35
@maxjacobson hmm, yeah I'm not sure why that would turn off this error messages. There are a few other preload related warnings that can happen, maybe it turned one of those (that look similar to this) off instead? If you ever want help digging into it, let me know. I'm happy to screen share/pair. 

---

@malclocke so glad you figured this out!  

---

Also, to anyone on this thread, I've been giving www.flippercloud.io credits to people who contribute (and helping debug/figure this out is definitely a contribution!). 

So if you want to check it out beyond the trial, let me know and I'll spot you several months.

Lastly, if you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard other than what you mentioned here).

If you aren't comfortable leaving that information here in a public comment, feel free to email me directly john@fewerandfaster.com. I'm just always curious. :)

**Comment by jnunemaker** [comment] 2021-11-04 18:36
Closing this issue since it doesn't seem to be with flipper. If anyone wants help tracking down the misbehaving middleware in their app, let me know.

**Closed by jnunemaker** 2021-11-04 18:36 UTC

**Comment by jnunemaker** [comment] 2021-11-04 18:40
@malclocke would you mind linking to the bug in scout's app middleware so I can see it?

**Comment by malclocke** [comment] 2021-11-04 22:09
@jnunemaker I haven't raised a bug with Scout yet, working on a minimal test case.  But the root of the problem is here https://github.com/scoutapp/scout_apm_ruby/blob/9ef573c2d1b3e286e3eba761be6218859bc2dc3c/lib/scout_apm/instant/middleware.rb#L180-L195

The `page` object there replaces the body in the rack stack and the reference to the `Rack::BodyProxy` that flipper creates is lost.

@bkeepers not really sure.  I think if you're using `Rack::BodyProxy` you are at the mercy of everything else in the stack to behave correctly as you pass the execution of that code block down the stack and you are relying on it to get called elsewhere.

**Comment by Linuus** [comment] 2021-11-09 07:23
After some more fiddling I found that I only get the warning in my tests for some reason 🤔

**Comment by bkeepers** [comment] 2021-11-10 14:57
@Linuus Thanks for the update. We'll look into it and see if there is an issue with teardown in tests. What test framework are you using? And which type of tests were causing the error?

**Comment by Linuus** [comment] 2021-11-11 08:02
> @Linuus Thanks for the update. We'll look into it and see if there is an issue with teardown in tests. What test framework are you using? And which type of tests were causing the error?

Minitest. It only showed up when running multiple controller tests (which makes sense since it's a middleware :)).
