### ISSUE TITLE
Lacking pretty output in `rake routes`

### ISSUE THREAD

**Issue by robKitson** [jnunemaker/flipper#117] opened 2016-04-26 18:01 UTC
Hey All,

When I run ```rake routes``` the line for ```/flipper``` looks like this (you may need to scroll to the right)
```
                                                      /flipper                                                                  #<Rack::Builder:0x007fbbe44200c0 @warmup=nil, @run=#<Proc:0x007fbbe443b9d8@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/flipper-ui-0.7.5/lib/flipper/ui.rb:31 (lambda)>, @map=nil, @use=[#<Proc:0x007fbbe4421d08@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/rack-1.6.4/lib/rack/builder.rb:86>, #<Proc:0x007fbbe4400040@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/rack-1.6.4/lib/rack/builder.rb:86>, #<Proc:0x007fbbe43f3f70@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/rack-1.6.4/lib/rack/builder.rb:86>, #<Proc:0x007fbbe43f3ea8@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/rack-1.6.4/lib/rack/builder.rb:86>, #<Proc:0x007fbbe43f3de0@/Users/rob/.rvm/gems/ruby-2.2.3@borg/gems/rack-1.6.4/lib/rack/builder.rb:86>]>
```

The route works fine when I hit it in my browser, so I'm wondering if anyone knows why this may be happening.

Thanks!

**Comment by jnunemaker** [comment] 2016-04-26 18:33
I don't think that is an error, it is just what Rack::Builder likes like from rails routes. Rack::Builder is what flipper [uses to make a mountable middleware](https://github.com/jnunemaker/flipper/blob/81f840ce485b3abc43d97d8354abc7fa957a223c/lib/flipper/ui.rb#L30-L41) for rails (or any rack app). I'm open to tweaking it somehow if it makes rake routes prettier, but I'm not really sure off hand what would be a good idea.

**Comment by jnunemaker** [comment] 2016-04-26 18:34
Closing as this is not a bug per say, but if anyone knows a way to make that output better off hand let me know.

**Comment by robKitson** [comment] 2016-04-26 18:36
Thanks John. You're right, it's not an error, sorry for the mis-categorization.

I'm not super-concerned with displaying pretty routes, just thought it may have been an oversight.

**Comment by jnunemaker** [comment] 2016-04-26 20:41
@robKitson I don't have time to look into it now, but I would like to pretty this up. I actually think I'd like to  re-open and change the title as a reminder to peek at some point.

**Comment by AlexWheeler** [comment] 2016-07-22 03:07
It looks like it has to do with mount being evaluated which calls ```Flipper::UI.app($flipper)``` and returns the builder instance, which `rake routes` then prints to the console.  For example if we change Flipper::IU.app($flipper) w/ a different Rack application we get

![screen shot 2016-07-21 at 10 49 48 pm](https://cloud.githubusercontent.com/assets/3260042/17045195/7e1596a4-4f95-11e6-8369-e9d747f8d868.png)

![screen shot 2016-07-21 at 10 49 19 pm](https://cloud.githubusercontent.com/assets/3260042/17045192/78932d7c-4f95-11e6-9617-9c594af47dcc.png)

I'll keep digging through the routes command and some other docs

**Comment by AlexWheeler** [comment] 2016-07-22 03:23
If we override inspect we could have it print whatever wanted, not quite sure if this is correct way yet
![screen shot 2016-07-21 at 11 22 45 pm](https://cloud.githubusercontent.com/assets/3260042/17045733/25f2ea94-4f9a-11e6-9472-99978ec702d3.png)
![screen shot 2016-07-21 at 11 22 07 pm](https://cloud.githubusercontent.com/assets/3260042/17045737/2ad13688-4f9a-11e6-8636-cf9cc8c36f98.png)

**Comment by AlexWheeler** [comment] 2016-07-22 20:07
Looking through the routes.rake source it does actually look like overriding inspect is the way to go

![draw_section](https://cloud.githubusercontent.com/assets/3260042/17069760/4f1d6ef8-5026-11e6-9994-fd890a7957ec.png)

![reqs](https://cloud.githubusercontent.com/assets/3260042/17069751/481b396e-5026-11e6-81cb-5e591a6947bf.png)

![endpoint](https://cloud.githubusercontent.com/assets/3260042/17069743/3ff47426-5026-11e6-9e42-e8530b80a394.png)

**Closed** 2016-07-23 13:09 UTC
